service: email-notifier
app: srvrless-training
org: umatbro

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8

functions:
  send-email:
    environment:
      ACCESS_KEY: ${param:ACCESS_KEY}
      SECRET_KEY: ${param:SECRET_KEY}
      EMAIL_FROM: ${param:EMAIL_FROM}
    handler: main.main
    events:
      - http:
          path: send-email
          method: post
